const axios = require('axios');
const crypto = require('crypto');
const APS = 'https://developer.api.autodesk.com';
function requireConfig() { const miss=[]; if(!process.env.APS_CLIENT_ID) miss.push('APS_CLIENT_ID'); if(!process.env.APS_CLIENT_SECRET) miss.push('APS_CLIENT_SECRET'); if(!process.env.APS_CALLBACK_URL) miss.push('APS_CALLBACK_URL'); if(!process.env.SESSION_SECRET) miss.push('SESSION_SECRET'); if(miss.length){const e=new Error('Missing environment variables: '+miss.join(', ')); e.status=400; throw e;} }
function basic(){return Buffer.from(`${process.env.APS_CLIENT_ID}:${process.env.APS_CLIENT_SECRET}`).toString('base64')}
function key(){return crypto.createHash('sha256').update(process.env.SESSION_SECRET).digest()}
function encrypt(obj){const iv=crypto.randomBytes(12);const cipher=crypto.createCipheriv('aes-256-gcm',key(),iv);const data=Buffer.concat([cipher.update(JSON.stringify(obj),'utf8'),cipher.final()]);const tag=cipher.getAuthTag();return Buffer.concat([iv,tag,data]).toString('base64url')}
function decrypt(v){try{const b=Buffer.from(v||'','base64url');const iv=b.subarray(0,12);const tag=b.subarray(12,28);const data=b.subarray(28);const decipher=crypto.createDecipheriv('aes-256-gcm',key(),iv);decipher.setAuthTag(tag);return JSON.parse(Buffer.concat([decipher.update(data),decipher.final()]).toString('utf8'))}catch{return null}}
function setCookie(res,name,value,maxAge=604800){res.setHeader('Set-Cookie',`${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`)}
function clearCookie(res,name){res.setHeader('Set-Cookie',`${name}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`)}
function getSession(req){const cookie=req.headers.cookie||'';const match=cookie.match(/(?:^|; )autodesk_session=([^;]+)/);return decrypt(match&&match[1])}
async function refresh(sess){const body=new URLSearchParams();body.set('grant_type','refresh_token');body.set('refresh_token',sess.refresh_token);body.set('scope','data:read account:read account:write');const r=await axios.post(`${APS}/authentication/v2/token`,body,{headers:{Authorization:`Basic ${basic()}`,'Content-Type':'application/x-www-form-urlencoded'}});return {access_token:r.data.access_token,refresh_token:r.data.refresh_token||sess.refresh_token,expires_at:Date.now()+((r.data.expires_in||3600)-60)*1000}}
async function userToken(req,res){requireConfig();let sess=getSession(req);if(!sess||!sess.access_token){const e=new Error('Autodesk is not connected.');e.status=401;throw e;}if(Date.now()>=sess.expires_at){sess=await refresh(sess);setCookie(res,'autodesk_session',encrypt(sess));}return sess.access_token}
async function twoLegged(){requireConfig();const body=new URLSearchParams();body.set('grant_type','client_credentials');body.set('scope','account:read account:write');const r=await axios.post(`${APS}/authentication/v2/token`,body,{headers:{Authorization:`Basic ${basic()}`,'Content-Type':'application/x-www-form-urlencoded'}});return r.data.access_token}
function account(hubId){return hubId&&hubId.startsWith('b.')?hubId.slice(2):hubId||''}
function normalizeState(country,state){const c=String(country||'').trim().toLowerCase();const s=String(state||'').trim();if(!s)return undefined;if(c==='australia'||c==='au'){const map={ACT:'Australian Capital Territory',NSW:'New South Wales',NT:'Northern Territory',QLD:'Queensland',SA:'South Australia',TAS:'Tasmania',VIC:'Victoria',WA:'Western Australia'};return map[s.toUpperCase()]||s}return s}
function error(res,e){res.status(e.status||e.response?.status||500).json({message:e.response?.data?.developerMessage||e.response?.data?.message||e.message||'Server error',details:e.response?.data||null})}
module.exports={axios,APS,requireConfig,basic,encrypt,setCookie,clearCookie,getSession,userToken,twoLegged,account,normalizeState,error};
